-- Generated by matugen from {{image}}
-- Do not edit - change the wallpaper, or the template in ~/.config/matugen.
--
-- hyprland.lua reads this with dofile() from rice.dir (~/.config/hypr) and
-- hands the table to the look block as `c`.
return {
    wallpaper  = [[{{image}}]],

    primary    = "rgb({{colors.primary.default.hex_stripped}})",
    onprimary  = "rgb({{colors.on_primary.default.hex_stripped}})",
    pcontainer = "rgb({{colors.primary_container.default.hex_stripped}})",
    secondary  = "rgb({{colors.secondary.default.hex_stripped}})",
    tertiary   = "rgb({{colors.tertiary.default.hex_stripped}})",
    error      = "rgb({{colors.error.default.hex_stripped}})",

    base       = "rgb({{colors.surface.default.hex_stripped}})",
    panel      = "rgb({{colors.surface_container.default.hex_stripped}})",
    raised     = "rgb({{colors.surface_container_high.default.hex_stripped}})",
    text       = "rgb({{colors.on_surface.default.hex_stripped}})",
    subtext    = "rgb({{colors.on_surface_variant.default.hex_stripped}})",
    outline    = "rgb({{colors.outline.default.hex_stripped}})",
    divider    = "rgb({{colors.outline_variant.default.hex_stripped}})",

    glass      = "rgba({{colors.surface_container.default.hex_stripped}}cc)",
}
